Update MainFlow.yml

diff --git a/.github/workflows/MainFlow.yml b/.github/workflows/MainFlow.yml
--- a/.github/workflows/MainFlow.yml
+++ b/.github/workflows/MainFlow.yml
@@ -44,27 +44,27 @@ jobs:
           dotnet build
           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
   
-  qualitiy:
-    name: Qualitiy gate check
-    needs: scan 
-    runs-on: ubuntu-22.04
+  # qualitiy:
+  #   name: Qualitiy gate check
+  #   needs: scan 
+  #   runs-on: ubuntu-22.04
     
-    steps:
-      - name: Quality Gate Check
-        run: |
-          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
-          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=LamersBart_Pridr-UserService")
-          echo "SonarCloud API Response: $RESPONSE"
-          STATUS=$(echo $RESPONSE | jq -r .projectStatus.status)
-          echo "Quality Gate Status: $STATUS"
-          if [ "$STATUS" != "OK" ]; then
-              echo "Quality Gate failed!"
-              exit 1
-          fi
+  #   steps:
+  #     - name: Quality Gate Check
+  #       run: |
+  #         RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+  #         "https://sonarcloud.io/api/qualitygates/project_status?projectKey=LamersBart_Pridr-UserService")
+  #         echo "SonarCloud API Response: $RESPONSE"
+  #         STATUS=$(echo $RESPONSE | jq -r .projectStatus.status)
+  #         echo "Quality Gate Status: $STATUS"
+  #         if [ "$STATUS" != "OK" ]; then
+  #             echo "Quality Gate failed!"
+  #             exit 1
+  #         fi
   
   build:
     name: Build and push docker image
-    needs: [scan, qualitiy]
+    needs: [scan]
     runs-on: ubuntu-22.04
     
     steps:
@@ -81,7 +81,7 @@ jobs:
       
   integration-tests:
     name: Trigger Integration Tests
-    needs: [scan, qualitiy, build]
+    needs: [scan, build]
     runs-on: ubuntu-22.04
 
     steps:
